### ISSUE TITLE
Do we need `.backward(retain_graph=True)`?

### ISSUE THREAD

**Issue by Beomi** [jlamprou/Infini-Attention#3]
I adapted my code with your gradient-accum based training code.

then I encoutered this issue:

```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

It seems like we backprop multiple times for segments, so I have to use turn on `retain_graph=True` but it consumes more memory, which contradicts the benefit of infini attention.

Didn't you encouter any issue related with?

**Comment by jlamprou** [comment]
@Beomi I changed my model implementation to pass the compressive memory to the output, and im passing it as input on my model forward and I'm also detaching M and z on def _update_memory since there is no need to keep them on the backward. Also check my training loop on run_clm.py to see at which point i do the backward. There is no need to retain the graph that way.

**Comment by Beomi** [comment]
@jlamprou I missed that point! (to detatch M and z), thanks for clarification :D it helped a lot.
