### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by riou-chen** [jlamprou/Infini-Attention#4]
how to train Qwen1.5-MoE-A2.7B in 8 A100 GPU?

**Comment by jlamprou** [comment]
@riou-chen The model pre-trained model may barely fit in an A100 40GB with 1 batch size , bf16 and an 8-bit optimizer. Otherwise if you have multiple A100s in parallel i suggest either mapping the model on the GPU or using FSDP with Accelerate. Lastly you could create QwenConfig with less parameters but you will have to pretrain it on billions of tokens before you get some good performance.
